// Import the wasm module (generated by wasm-pack)
import init, { greet } from './pkg/wasm_test.js';

async function run() {
    // Initialize the WASM module
    await init();

    // Call the WASM function
    greet('蔡豪');

    // Display the result on the web page
}

run().catch(console.error);
